name: Build Go Program for Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # 确保 Go 版本有效

      - name: Build for Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o go-diary-linux-amd64 .

      - name: Upload Linux amd64 binary
        uses: actions/upload-artifact@v3.1.3  # 明确指定具体版本
        with:
          name: go-diary-linux-amd64
          path: go-diary-linux-amd64

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build for Linux arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -o go-diary-linux-arm64 .
      - name: Upload Linux arm64 binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: go-diary-linux-arm64
          path: go-diary-linux-arm64

  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build for Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o go-diary-windows-amd64.exe .
      - name: Upload Windows amd64 binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: go-diary-windows-amd64
          path: go-diary-windows-amd64.exe

  build-windows-arm64:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build for Windows arm64
        run: |
          GOOS=windows GOARCH=arm64 go build -o go-diary-windows-arm64.exe .
      - name: Upload Windows arm64 binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: go-diary-windows-arm64
          path: go-diary-windows-arm64.exe

  build-macos-amd64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build for macOS amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o go-diary-darwin-amd64 .
      - name: Upload macOS amd64 binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: go-diary-darwin-amd64
          path: go-diary-darwin-amd64

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build for macOS arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o go-diary-darwin-arm64 .
      - name: Upload macOS arm64 binary
        uses: actions/upload-artifact@v3.1.3
        with:
          name: go-diary-darwin-arm64
          path: go-diary-darwin-arm64