name: Build and Release Multi-Platform Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write  # 必须授予写入权限才能创建 Release

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5  # 使用最新 v5 版本
        with:
          go-version: '1.22.5'    # 确保与你的实际版本一致

      - name: Build Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o ./dist/go-diary-linux-amd64 .

      - name: Build Linux arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -o ./dist/go-diary-linux-arm64 .

      - name: Build Windows amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o ./dist/go-diary-windows-amd64.exe .

      - name: Build Windows arm64
        run: |
          GOOS=windows GOARCH=arm64 go build -o ./dist/go-diary-windows-arm64.exe .

      - name: Build macOS amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ./dist/go-diary-darwin-amd64 .

      - name: Build macOS arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o ./dist/go-diary-darwin-arm64 .

      - name: Generate Checksums
        run: |
          cd ./dist
          shasum -a 256 * > checksums.txt

      - name: Create Release Draft
        id: create-release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          commitish: ${{ github.sha }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          files: |
            ./dist/go-diary-*
            ./dist/checksums.txt
          tag_name: ${{ steps.create-release.outputs.tag_name }}
          name: ${{ steps.create-release.outputs.name }}