name: Go Build

on:
  push:
    branches: [ "main" ]  # 监听main分支的推送
  pull_request:
    branches: [ "main" ]  # 监听针对main分支的PR

jobs:
  build:
    name: Build and Verify
    runs-on: ubuntu-latest  # 使用Ubuntu系统作为编译环境

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出你的代码

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # 指定你的Go版本（根据项目要求修改）

      - name: Install Dependencies
        run: go mod download  # 下载依赖（如果使用Go Modules）

      - name: Build
        run: go build -v ./...  # 编译整个项目，验证是否通过